export const actionTypes = {
  FETCHINH_START: "FETCHINH_START",
  FETCHINH_SUCCESS: "FETCHINH_SUCCESS",
  FETCHINH_ERROR: "FETCHINH_ERROR",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
};
